model:
  _target_: src.models.SASRec
  args:
    hidden_units: 50
    num_blocks: 2
    num_heads: 1
    dropout_rate: 0.5
    maxlen: 50
    l2_emb: 0.0
    device: mps

trainer:
  max_len: 50
  batch_size: 128
  n_epochs: 100
  l2_emb: 5e-5
  weight_decay: 0.0001
  val_freq: 5
  save_freq: 5
  # early_stopping:
  #   enabled: false
  #   patience: 10
  #   min_delta: 0.001
  device: mps # device name or "auto"
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 15
  gamma: 0.95
  # _target_: torch.optim.lr_scheduler.OneCycleLR
  # max_lr: 7e-4
  # pct_start: 0.1
  # steps_per_epoch: ${trainer.epoch_len}
  # epochs: ${trainer.n_epochs}
  # anneal_strategy: cos

loss_function:
  _target_: torch.nn.BCEWithLogitsLoss

# self.config["trainer"]["max_grad_norm"]

wandb:
  project: "federative_learning"
  log_checkpoints: True
  entity: null
  run_name: "office"
  mode: "online"
  config:
    optimizer: AdamW
  # loss_names: ["loss"]